BE-035 Hanna Kalashnyk DiscountTests
SergeyKoval/2021_june_team4_be pull request #103
Opened 2021-07-23 07:22 UTC by Hanna-Kalashnyk

2021-07-23 07:56 UTC, Artem-Kishenets approved these changes, later dismissed
🍰

2021-07-23 08:00 UTC, rudik-byte approved these changes, later dismissed

2021-07-23 08:35 UTC, Artem-Kishenets approved these changes, later dismissed

2021-07-23 10:13 UTC, mikevoloshyn requested changes, later dismissed

2021-07-23 10:13 UTC, mikevoloshyn commented on src/test/java/com/exadel/discount/controller/DiscountTests.java
> +    public void deleteDiscountAndCheckIT() throws Exception {
this test actually consists of 3 tests(test delete, test if archived and test restore.),  Please name it properly or split it into 3 tests

2021-07-26 11:35 UTC, Artem-Kishenets approved these changes

2021-07-26 11:37 UTC, rudik-byte approved these changes

2021-07-26 11:43 UTC, SergeyKoval approved these changes

2021-07-26 15:56 UTC, merged