Mvc structure
SergeyKoval/2021_june_team4_be pull request #16
Opened 2021-06-14 14:13 UTC by Hanna-Kalashnyk

User+coupon entities. Delete requests return 500 yet.

2021-06-14 14:33 UTC, Hanna-Kalashnyk commented
tried to remove conflicts

2021-06-14 15:32 UTC, el-dub requested changes

2021-06-14 15:32 UTC, el-dub commented on .mvn/wrapper/MavenWrapperDownloader.java
> +/*
I think we shouldn't include this. Add .mvn to gitignore

2021-06-14 15:32 UTC, el-dub commented on src/main/java/com/exadel/discount/entity/Coupon.java
> +
You can use Lombok's @NoArgsConstructor instead of this

2021-06-14 15:32 UTC, el-dub commented on src/main/java/com/exadel/discount/service/UserServiceImpl.java
> +    }
We can't edit our users, it's uncahngable information from DB

2021-06-14 15:32 UTC, el-dub commented on src/main/java/com/exadel/discount/controller/UserController.java
> +
We can't add users, we have this information from the company DB

2021-06-14 15:32 UTC, el-dub commented on src/main/java/com/exadel/discount/controller/UserController.java
> +    }
Also can't delete or edit

2021-06-15 08:44 UTC, closed without merging

2021-06-15 08:45 UTC, Hanna-Kalashnyk commented
I'll open soon it with Favourite part and some editions