BE-006-1 (Nikolay Chornyi) Add entity, DTO
SergeyKoval/2021_june_team4_be pull request #29
Opened 2021-06-30 18:12 UTC by n-chornyi

Add entities, DTOs & update table discounts

2021-06-30 19:24 UTC, el-dub commented on src/main/java/com/exadel/discount/entity/Vendor.java
> +@ToString(exclude = {"vendorLocations"})
Add discounts

2021-06-30 19:24 UTC, el-dub commented on src/main/java/com/exadel/discount/entity/Discount.java
>  @ToString(exclude = {"tags"})
Add vendorLocations

2021-06-30 19:26 UTC, n-chornyi commented on src/main/java/com/exadel/discount/entity/Vendor.java
> +@ToString(exclude = {"vendorLocations"})
+

2021-06-30 19:26 UTC, mblack666 commented on src/main/java/com/exadel/discount/entity/Discount.java
>  @ToString(exclude = {"tags"})
+

2021-06-30 19:31 UTC, el-dub approved these changes, later dismissed

2021-06-30 19:37 UTC, Hanna-Kalashnyk commented on src/main/resources/db/changelog/v.0.3/db.changelog-add-vendor-to-discount.yaml
> +      id: 37-add-vendor-to-dixount
is here no typo in word  "dixount" ?

2021-06-30 19:47 UTC, Hanna-Kalashnyk approved these changes, later dismissed

2021-06-30 19:47 UTC, n-chornyi commented on src/main/resources/db/changelog/v.0.3/db.changelog-add-vendor-to-discount.yaml
> +      id: 37-add-vendor-to-dixount
+

2021-07-01 09:59 UTC, el-dub commented on src/main/java/com/exadel/discount/dto/vendor/CreateVendorDTO.java
> +    @Size(max = 50)
Add messages

2021-07-01 16:14 UTC, n-chornyi commented on src/main/java/com/exadel/discount/dto/vendor/CreateVendorDTO.java
> +    @Size(max = 50)
+

2021-07-01 16:18 UTC, el-dub submitted a review, later dismissed

2021-07-02 08:11 UTC, mikevoloshyn requested changes

2021-07-02 08:11 UTC, mikevoloshyn commented on src/main/java/com/exadel/discount/controller/VendorController.java
>  public class VendorController {
empty controller

2021-07-02 08:11 UTC, mikevoloshyn commented on src/main/java/com/exadel/discount/dto/CategoryDTO.java
> +
empty line

2021-07-02 08:11 UTC, mikevoloshyn commented on src/main/java/com/exadel/discount/dto/location/CreateLocationDTO.java
>      private String contact;
please remove todo lines

2021-07-02 08:38 UTC, n-chornyi commented on src/main/java/com/exadel/discount/dto/location/CreateLocationDTO.java
>      private String contact;
+

2021-07-02 08:40 UTC, n-chornyi commented on src/main/java/com/exadel/discount/dto/CategoryDTO.java
> +
+

2021-07-02 08:45 UTC, el-dub approved these changes

2021-07-02 09:55 UTC, mikevoloshyn approved these changes

2021-07-02 10:10 UTC, mikevoloshyn approved these changes

2021-07-02 10:13 UTC, rudik-byte approved these changes

2021-07-02 10:20 UTC, SerhiiPakulia approved these changes

2021-07-02 10:46 UTC, merged