Project structure
SergeyKoval/2021_june_team4_be pull request #3
Opened 2021-06-02 17:13 UTC by el-dub

Add maven configuration and test controller.

2021-06-02 18:26 UTC, rudik-byte submitted a review, later dismissed

2021-06-03 04:53 UTC, SergeyKoval requested changes

2021-06-03 04:53 UTC, SergeyKoval commented on pom.xml
> +    <groupId>com.discount</groupId>
group id should contain information about organization. com.exade as example

2021-06-03 04:53 UTC, SergeyKoval commented on pom.xml
> +    <artifactId>2021_june_team4_be</artifactId>
artifact id should specify some product name. discount as example

2021-06-03 04:53 UTC, SergeyKoval commented on pom.xml
> +            <version>1.18.20</version>
move version to properties

2021-06-03 04:53 UTC, SergeyKoval commented on pom.xml
> +            <version>4.13.2</version>
move version to properties

2021-06-03 04:53 UTC, SergeyKoval commented on src/main/java/com/discount/Application.java
> +package com.discount;
change package structure based on pom group id and artifact id: com.exadel.discount

2021-06-03 05:55 UTC, rudik-byte approved these changes

2021-06-03 05:57 UTC, rudik-byte approved these changes, later dismissed

2021-06-03 07:27 UTC, SergeyKoval commented on pom.xml
> +    <artifactId>Discount</artifactId>
```suggestion
    <artifactId>discount</artifactId>
```

2021-06-03 07:28 UTC, SergeyKoval commented on src/main/java/com/exadel/discount/Application.java
> +public class Application {
```suggestion
public class DiscountApplication {
```

2021-06-03 07:41 UTC, rudik-byte approved these changes

2021-06-03 07:57 UTC, SergeyKoval approved these changes

2021-06-03 08:30 UTC, merged