Added Swagger and Vendor controller (Elizaveta Dubogryz)
SergeyKoval/2021_june_team4_be pull request #5
Opened 2021-06-04 19:33 UTC by el-dub

2021-06-04 19:40 UTC, Artem-Kishenets submitted a review, later dismissed
Changes were agreed upon between me and the given programmer.

2021-06-07 10:24 UTC, Artem-Kishenets approved these changes, later dismissed
Ювелирная работа

2021-06-07 11:31 UTC, SergeyKoval requested changes

2021-06-07 11:31 UTC, SergeyKoval commented on src/main/java/com/exadel/discount/controller/VendorController.java
> +    public ResponseEntity<List<BaseVendorDTO>> getVendorsList() {
You need ResponseEntity only if you want to set status code dynamically (or something similar)

2021-06-07 11:31 UTC, SergeyKoval commented on src/main/java/com/exadel/discount/controller/VendorController.java
> +    public ResponseEntity<DetailedVendorDTO> getVendorById(@PathVariable(name = "vendorId") long id) {
Introduce spring validation. vendorId is required here

2021-06-07 11:32 UTC, SergeyKoval commented on src/main/java/com/exadel/discount/controller/VendorController.java
> +    public ResponseEntity<DetailedVendorDTO> getVendorById(@PathVariable(name = "vendorId") long id) {
Or you can leave as it is and create separate task to introduce spring validation

2021-06-08 19:22 UTC, Artem-Kishenets approved these changes
I do not see any errors, so this commit has a right to be on the origin branch

2021-06-09 05:07 UTC, el-dub commented on src/main/java/com/exadel/discount/controller/VendorController.java
> +    public ResponseEntity<List<BaseVendorDTO>> getVendorsList() {
+

2021-06-09 05:08 UTC, el-dub commented on src/main/java/com/exadel/discount/controller/VendorController.java
> +    public ResponseEntity<DetailedVendorDTO> getVendorById(@PathVariable(name = "vendorId") long id) {
+

2021-06-09 07:51 UTC, SergeyKoval approved these changes

2021-06-09 08:21 UTC, merged