BE-033 Add archiving for vendors (Elizaveta Dubogryz)
SergeyKoval/2021_june_team4_be pull request #50
Opened 2021-07-06 05:56 UTC by el-dub

2021-07-06 06:58 UTC, n-chornyi submitted a review, later dismissed

2021-07-06 07:36 UTC, SergeyKoval requested changes
I suggest to change a bit scenario of deleting. For now you are getting full entity in order to check if it exists, then update it (entity) and save (entity). It could cause unexpected effects on saving for the reference entities and on getting could cause additional joins. 
My suggestion scenario is next:

1. To check if entity exists add specific query to DB which will return actually boolean
2. Add specific update query to DB in order to update just one field in the table

Change it here and create trello ticket in order to update other similar scenarios.

2021-07-06 10:58 UTC, rudik-byte submitted a review, later dismissed

2021-07-06 15:58 UTC, rudik-byte approved these changes

2021-07-07 07:46 UTC, SergeyKoval approved these changes

2021-07-07 07:51 UTC, merged