Docker compose1.5 (Anton Rudkovskyi)
SergeyKoval/2021_june_team4_be pull request #8
Opened 2021-06-08 12:34 UTC by rudik-byte

Edit docker_compose
Added new service for docker_compose

2021-06-08 16:26 UTC, el-dub submitted a review, later dismissed

2021-06-09 07:54 UTC, SergeyKoval requested changes

2021-06-09 07:54 UTC, SergeyKoval commented on docker-compose.yml
> +    links:
Links is deprecated now, use depends_on

2021-06-09 07:55 UTC, SergeyKoval commented
Your backend service is not using db. Please connect them and review, that it starts without any issues

2021-06-10 08:10 UTC, rudik-byte commented on docker-compose.yml
> +    links:
Done

2021-06-10 08:50 UTC, SerhiiPakulia submitted a review, later dismissed

2021-06-10 11:26 UTC, el-dub approved these changes

2021-06-10 12:38 UTC, el-dub submitted a review, later dismissed

2021-06-10 13:08 UTC, SergeyKoval requested changes

2021-06-10 13:08 UTC, SergeyKoval commented on src/main/resources/application.yml
> +      url:${POSTGRES_DB_URL}
It is bad approach. Your application yml doesn't know about docker compose environment variables. Specify url here directly

2021-06-10 13:08 UTC, SergeyKoval commented on docker-compose.yml
> +  backend:
You should pass correct environment variables for the backend service. It should be at least url (which will be different from your application.yml specified. Read about using another docker compose service as part of the url

2021-06-14 08:17 UTC, closed without merging