BE-038-1 (Nikolay)  Add update (Discount)
SergeyKoval/2021_june_team4_be pull request #83
Opened 2021-07-14 08:41 UTC by n-chornyi

2021-07-14 09:11 UTC, Hanna-Kalashnyk submitted a review, later dismissed

2021-07-14 14:37 UTC, SergeyKoval requested changes, later dismissed

2021-07-14 14:37 UTC, SergeyKoval commented on src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
> +        return discountRepository.findById(id).map(discount -> {
stream's map method become too complicated, should be refactored

2021-07-14 20:34 UTC, Hanna-Kalashnyk submitted a review, later dismissed

2021-07-15 13:02 UTC, SergeyKoval submitted a review, later dismissed

2021-07-15 20:22 UTC, Hanna-Kalashnyk approved these changes

2021-07-20 08:29 UTC, mikevoloshyn approved these changes

2021-07-20 08:48 UTC, merged